### ISSUE TITLE
Start from top of page when moving to next page

### ISSUE THREAD

**Issue by ghost** [joonne/harbour-nayttamo#21]
When the "Next page" is loaded, the list position is set to the bottom, so now the user needs to first scroll up to the list and then back down to go to the next page.

**Comment by joonne** [comment]
Thanks for commenting! Will be fixed in next release :+1:

**Comment by mlehtima** [comment]
I have plans to remove the Next/Previous page handling and make new content load automatically. It shouldn't be too difficult, just appending new data to the list model based on new query with new offset.
