### ISSUE TITLE
API keys can be easily obtained by modifying qml/js code on device

### ISSUE THREAD

**Issue by mlehtima** [joonne/harbour-nayttamo#3]
At least url decryption should be done in c++ code to make it a little less trivial to obtain the secret decrypt key.

**Comment by joonne** [comment]
Do you happen to know if it is possible to make use of Qt Quick Compiler on Sailfish? I'd really like to know & try it out and it would solve this issue also if that is possible.

http://doc.qt.io/QtQuickCompiler/

**Comment by mlehtima** [comment]
I'll investigate what is the best way to make sure the decrypt key is not easily obtained from QML.

**Comment by joonne** [comment]
Any news on this? :)

**Comment by mlehtima** [comment]
Sorry about that, I have been doing too much other projects. I have had the code almost ready for a long time, just need to make sure the key is not easily obtained using "strings" command from the binary. I'll try to get this done soon so we can release initial version of the app.
